language: go
go:
  - 1.4
  - 1.5

services:
  - redis-server

install:
  - sudo go get -v ./...
  - sudo go get github.com/stretchr/testify/assert
  - sudo chmod +x ./test.sh
script:
  - sudo ./test.sh