language: go
go:
  - 1.4
  - 1.5

sudo: required

services:
  - redis-server

install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - export SERV="ant-worker"
  - go build
  - sudo ./$SERV install
  - sudo ./$SERV start
script:
  - go test ./... -v